### ISSUE TITLE
Lustre can fail to mount the buffer on a compute node

### ISSUE THREAD

**Issue by jsteel44** [RSE-Cambridge/data-acc#119]
We are seeing an issue occasionally where a job will hit an error "Burst buffer pre_run error". I see this in the dacd journal:

```
Jan 09 13:38:07 dac-e-19 dacd[57485]: SSH to: cpu-e-335 with command: mount -t lustre -o flock,nodev,nosuid dac-e-19-opa@o2ib1:/RTsjlttY /mnt/dac/6038_job
Jan 09 13:38:08 dac-e-19 dacd[57485]: Error in remote ssh run: 'mount -t lustre -o flock,nodev,nosuid dac-e-19-opa@o2ib1:/RTsjlttY /mnt/dac/6038_job' error: exit status 16
Jan 09 13:38:08 dac-e-19 dacd[57485]: Warning: Permanently added 'cpu-e-335,10.43.1.79' (ECDSA) to the list of known hosts.
                                      mount.lustre: mount dac-e-19-opa@o2ib1:/RTsjlttY at /mnt/dac/6038_job failed: Device or resource busy
                                      Is the backend filesystem mounted?
                                      Check /etc/mtab and /proc/mounts
```
This _might_ be due to the compute node mounting other file systems at the same time (at least that is how I can replicate the issue). In any case, should we add a retry, or put in a locking mechanism here to avoid this bombing out?

**Comment by JohnGarbutt** [comment]
it does seem worth retrying this, but it would be better if we can get some logs from lustre and get lustre folks to decide what is causing this problem.

**Comment by jsteel44** [comment]
Since the race condition fix I haven't seen this issue. I'll look further into this if it happens again.
