### ISSUE TITLE
Burst buffer path environment variables are inconsistent

### ISSUE THREAD

**Issue by jsteel44** [RSE-Cambridge/data-acc#78]
$DW_JOB_STRIPED includes the "global" directory in the path.
$DW_PERSISTENT_jobname does not, so users must specify $DW_PERSISTENT_jobname/global when using persistent buffers.

Can we make the behaviour of these consistent?

**Comment by JohnGarbutt** [comment]
They should be no need to specify /global for persistent buffers, as the mount is always global.

Why do you see the need to append /global? I am not sure that directly should actually exisit, or maybe I mounted it in the wrong place?

**Comment by jsteel44** [comment]
The global directory exists in the persistent buffer and users cannot write above that level, eg:

```
$ cd $DW_PERSISTENT_jobname
$ ls
global
$ touch test
touch: cannot touch ‘test’: Permission denied
$ touch global/test
$ ls global
test
```

**Comment by JohnGarbutt** [comment]
ah, OK. Got it. thanks.

**Comment by JohnGarbutt** [comment]
this should now be fixed, and the unit test was finally added in this commit: https://github.com/RSE-Cambridge/data-acc/commit/56f6096f0bef825a7d00c16477b394edbc4fd137

**Comment by jsteel44** [comment]
This has been resolved thanks.
