### ISSUE TITLE
Persistent burst buffer environment variable cannot be used for stage in/out

### ISSUE THREAD

**Issue by jsteel44** [RSE-Cambridge/data-acc#80]
Specifying something like:

`#DW stage_out source=$DW_PERSISTENT_STRIPED_mybuffer/myfile destination=[...snip...]`

Attempts to copy /myfile so it looks like that environment variable is not set. That environment variable can be used in the job successfully, just not in stage in or out definitions.

Note that I can successfully use the $DW_JOB_STRIPED environment variable for per-job buffers in the stage in and out definitions so I was expecting the persistent one to also work in the same way.

**Comment by JohnGarbutt** [comment]
needs testing, but it should be fixed in this commit:
https://github.com/RSE-Cambridge/data-acc/commit/3efb0b57f66bb3845095c7273397bc09fa064655

**Comment by jsteel44** [comment]
This has been resolved thanks.
