### ISSUE TITLE
Per-job buffers are not unmounted when the job ends

### ISSUE THREAD

**Issue by jsteel44** [RSE-Cambridge/data-acc#93]
I am seeing this issue on the compute nodes.

Also after unmounting we should issue an "rm -df" on the mountpoint to tidy up that directory without recursing into it (which should not be necessary). This also goes for persistent buffers; they are currently unmounted but not removed.

**Comment by JohnGarbutt** [comment]
still need to do "rm -df" but hopefully unmount now happens correctly.

**Comment by jsteel44** [comment]
This is working now and I have created a pull request for the "rm -df", thanks.
